sudo: required
dist: trusty

language: node_js
node_js:
  - "10"

services:
  - docker

install:
  - npm ci .
  - npm run build
  - npm run lint

script:
  # require the branch name to be master (note for PRs this is the base branch name)
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_retry docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    npm prune --production;
    travis_retry docker build -t $DOCKER_USERNAME/$SERVICE:$TRAVIS_BRANCH -f ./docker/Dockerfile .;
    travis_retry docker push $DOCKER_USERNAME/$SERVICE:$TRAVIS_BRANCH;
    fi

after_success: true
